### ISSUE TITLE
1.20.4 update?

### ISSUE THREAD

**Issue by GIToez** [ASangarin/AriKeys#12]
Was just seeing what's the possibility of getting this updated 1.20.4

**Comment by Pryzmm** [comment]
yes please; i need more supported versions for my recreation of guitar hero in minecraft :3

**Comment by ASangarin** [comment]
Working on it.

**Comment by SlayorPlayz** [comment]
Could u add folia support too?

**Comment by luneflu** [comment]
Hello, you might want to try my fork instead for newer version.

https://github.com/alvindimas05/AriKeys

**Comment by appleLPG** [comment]
> Hello, you might want to try my fork instead for newer version.
> 
> https://github.com/alvindimas05/AriKeys

Your fork fixed a bug where the button could not be found.
Can you backport to 1.20.1?

**Comment by Flux-Client** [comment]
1.21?

**Comment by ASangarin** [comment]
A version for 1.20.4 has been released.
1.20.6, 1.21 and 1.21.3 are coming.
